//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int review_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string review_text { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
